plugins {
    id 'application'
    id ('com.gradleup.shadow') version '9.4.1'
}

dependencies {
    implementation project(":modpack-director-standalone")
    implementation project(":modpack-director-modlauncher")
    implementation project(":modpack-director-launchwrapper")
}

jar {
    manifest {
        attributes([
                "TweakClass"            : "com.juanmuscaria.modpackdirector.launchwrapper.ModpackDirectorTweaker",
                "TweakOrder"            : Integer.MIN_VALUE,
                "Specification-Title"   : "ModDirector",
                "Specification-Vendor"  : "Janrupf",
                "Specification-Version" : 1,
                "Implementation-Title"  : "ModpackDirectorUniversal",
                "Implementation-Vendor" : "juanmuscaria",
                "Implementation-Version": archiveVersion.get()
        ])
    }
}

build {
    dependsOn(shadowJar)
}

shadowJar {
    exclude('META-INF/versions/**')
}

application {
    mainClass = 'net.jan.moddirector.standalone.ModDirectorStandalone'
}